// Generated by CoffeeScript 1.9.3
(function() {
  var ESDBC, config, test;

  test = require('unit.js');

  ESDBC = require('../lib/esdbc');

  config = {
    libs: ['lib/sqlite-jdbc-3.8.11.2.jar'],
    className: 'org.sqlite.JDBC',
    url: 'jdbc:sqlite:test.db'
  };

  describe('ESDBC', function() {
    return it('Connection', function() {
      var esdbc;
      esdbc = new ESDBC(config);
      return test.promise.given(function() {
        return esdbc.getConnection();
      }).then(function(connection) {
        test.must(connection.isValid(2)).be(true);
        test.must(connection.isClosed()).be(false);
        return connection.close().then(function() {
          return connection;
        });
      }).then(function(connection) {
        test.must(connection.isValid(2)).be(false);
        test.must(connection.isClosed()).be(true);
        return connection;
      });
    });
  });

}).call(this);
