// Generated by CoffeeScript 1.10.0
(function() {
  var NodeJDBC, config, test;

  test = require('unit.js');

  NodeJDBC = require('../lib/nodejdbc');

  config = {
    libs: ['lib/sqlite-jdbc-3.8.11.2.jar'],
    className: 'org.sqlite.JDBC',
    url: 'jdbc:sqlite:test.db'
  };

  describe('NodeJDBC', function() {
    return it('Connection', function() {
      var nodejdbc;
      nodejdbc = new NodeJDBC(config);
      return test.promise.given(function() {
        return nodejdbc.getConnection();
      }).then(function(connection) {
        test.must(connection.isValid(2)).be(true);
        test.must(connection.isClosed()).be(false);
        return connection.close().then(function() {
          return connection;
        });
      }).then(function(connection) {
        test.must(connection.isValid(2)).be(false);
        test.must(connection.isClosed()).be(true);
        return connection;
      });
    });
  });

}).call(this);
