// Generated by CoffeeScript 1.10.0
(function() {
  var PreparedStatement, Promise, ResultSet, java;

  Promise = require('bluebird');

  ResultSet = require('./resultset');

  java = Promise.promisifyAll(require('java'));

  module.exports = PreparedStatement = (function() {
    function PreparedStatement(preparedStatement) {
      this.preparedStatement = Promise.promisifyAll(preparedStatement);
    }

    PreparedStatement.prototype.setString = function(index, value) {
      return this.preparedStatement.setStringSync(index, value);
    };

    PreparedStatement.prototype.setInt = function(index, value) {
      return this.preparedStatement.setIntSync(index, value);
    };

    PreparedStatement.prototype.setTimestamp = function(index, value) {
      var timestamp;
      timestamp = java.callStaticMethodSync("java.sql.Timestamp", 'valueOf', value);
      return this.preparedStatement.setTimestampSync(index, timestamp);
    };

    PreparedStatement.prototype.executeUpdate = function() {
      return this.preparedStatement.executeUpdateAsync();
    };

    PreparedStatement.prototype.executeUpdateSync = function() {
      return this.preparedStatement.executeUpdateSync();
    };

    PreparedStatement.prototype.addBatch = function() {
      return this.preparedStatement.addBatchAsync();
    };

    PreparedStatement.prototype.addBatchSync = function() {
      return this.preparedStatement.addBatchSync();
    };

    PreparedStatement.prototype.executeBatch = function() {
      return this.preparedStatement.executeBatchAsync();
    };

    PreparedStatement.prototype.executeBatchSync = function() {
      return this.preparedStatement.executeBatchSync();
    };

    PreparedStatement.prototype.executeQuery = function() {
      return this.preparedStatement.executeQueryAsync().then(function(resultSet) {
        return new ResultSet(resultSet);
      });
    };

    PreparedStatement.prototype.close = function() {
      return this.preparedStatement.closeAsync();
    };

    return PreparedStatement;

  })();

}).call(this);
