// Generated by CoffeeScript 1.10.0
(function() {
  var PreparedStatement, Promise, ResultSet;

  Promise = require('bluebird');

  ResultSet = require('./resultset');

  module.exports = PreparedStatement = (function() {
    function PreparedStatement(preparedStatement) {
      this.preparedStatement = Promise.promisifyAll(preparedStatement);
    }

    PreparedStatement.prototype.setString = function(index, value) {
      return this.preparedStatement.setStringSync(index, value);
    };

    PreparedStatement.prototype.setInt = function(index, value) {
      return this.preparedStatement.setIntSync(index, value);
    };

    PreparedStatement.prototype.executeUpdate = function() {
      return this.preparedStatement.executeUpdateAsync();
    };

    PreparedStatement.prototype.executeUpdateSync = function() {
      return this.preparedStatement.executeUpdateAsync();
    };

    PreparedStatement.prototype.executeQuery = function() {
      return this.preparedStatement.executeQueryAsync().then(function(resultSet) {
        return new ResultSet(resultSet);
      });
    };

    PreparedStatement.prototype.close = function() {
      return this.preparedStatement.closeAsync();
    };

    return PreparedStatement;

  })();

}).call(this);
