// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, ResultSet, ResultSetMetaData;

  Promise = require('bluebird');

  ResultSetMetaData = require('./rsmd');

  module.exports = ResultSet = (function() {
    function ResultSet(resultSet) {
      this.resultSet = Promise.promisifyAll(resultSet);
    }

    ResultSet.prototype.next = function() {
      return this.resultSet.nextSync();
    };

    ResultSet.prototype.getString = function(column) {
      return this.resultSet.getStringSync(column);
    };

    ResultSet.prototype.getInt = function(column) {
      return this.resultSet.getIntSync(column);
    };

    ResultSet.prototype.getTimestamp = function(column) {
      var timestamp;
      timestamp = this.resultSet.getTimestampSync(column);
      return timestamp.toString();
    };

    ResultSet.prototype.getMetaData = function() {
      return new ResultSetMetaData(this.resultSet.getMetaDataSync());
    };

    return ResultSet;

  })();

}).call(this);
