// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, ResultSet;

  Promise = require('bluebird');

  module.exports = ResultSet = (function() {
    function ResultSet(resultSet) {
      this.resultSet = Promise.promisifyAll(resultSet);
    }

    ResultSet.prototype.next = function() {
      return this.resultSet.nextSync();
    };

    ResultSet.prototype.getString = function(column) {
      return this.resultSet.getStringSync(column);
    };

    ResultSet.prototype.getInt = function(column) {
      return this.resultSet.getStringSync(column);
    };

    return ResultSet;

  })();

}).call(this);
