// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, ResultSet, Statement;

  Promise = require('bluebird');

  ResultSet = require('./resultset');

  module.exports = Statement = (function() {
    function Statement(statement) {
      this.statement = Promise.promisifyAll(statement);
    }

    Statement.prototype.executeUpdate = function(sql) {
      return this.statement.executeUpdateAsync(sql);
    };

    Statement.prototype.executeUpdateSync = function(sql) {
      return this.statement.executeUpdateAsync(sql);
    };

    Statement.prototype.executeQuery = function(sql) {
      return this.statement.executeQueryAsync(sql).then(function(resultSet) {
        return new ResultSet(resultSet);
      });
    };

    Statement.prototype.addBatch = function(sql) {
      return this.statement.addBatchAsync(sql);
    };

    Statement.prototype.addBatchSync = function(sql) {
      return this.statement.addBatchSync(sql);
    };

    Statement.prototype.executeBatch = function() {
      return this.statement.executeBatchAsync();
    };

    Statement.prototype.executeBatchSync = function() {
      return this.statement.executeBatchSync();
    };

    Statement.prototype.setQueryTimeout = function(seconds) {
      return this.statement.setQueryTimeoutSync(secods);
    };

    Statement.prototype.close = function() {
      return this.statement.closeAsync();
    };

    return Statement;

  })();

}).call(this);
